### ISSUE TITLE
nead or MacOS issue?

### ISSUE THREAD

**Issue by jasonebox** [BaptisteVandecrux/GC-Net-evaluation#19]
``` python
runcell('Comparison at EastGRIP', '/Users/jason/Dropbox/AWS/GC-Net-evaluation/GC-Net-evaluation.py')
Traceback (most recent call last):

  File "/Users/jason/Dropbox/AWS/GC-Net-evaluation/GC-Net-evaluation.py", line 146, in <module>
    gnl.plot_comp(df_all, df_interpol, varname1, varname2,varname3,'PROMICE', station+'_temp')

  File "/Users/jason/Dropbox/AWS/GC-Net-evaluation/gcnet_lib.py", line 94, in plot_comp
    'b',label= 'GC-Net')

  File "/Users/jeb/anaconda3/envs/s/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1667, in plot
    self.add_line(line)

  File "/Users/jeb/anaconda3/envs/s/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 1902, in add_line
    self._update_line_limits(line)

  File "/Users/jeb/anaconda3/envs/s/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 1924, in _update_line_limits
    path = line.get_path()

  File "/Users/jeb/anaconda3/envs/s/lib/python3.7/site-packages/matplotlib/lines.py", line 1027, in get_path
    self.recache()

  File "/Users/jeb/anaconda3/envs/s/lib/python3.7/site-packages/matplotlib/lines.py", line 670, in recache
    x = _to_unmasked_float_array(xconv).ravel()

  File "/Users/jeb/anaconda3/envs/s/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 1390, in _to_unmasked_float_array
    return np.asarray(x, float)

  File "/Users/jeb/anaconda3/envs/s/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)

TypeError: float() argument must be a string or a number, not 'Timestamp'
```

**Comment by BaptisteVandecrux** [comment]
Two things to try:

1) Potential issue with pandas library. I am using v1.1.3. What about you?
Maybe try:
`conda update --all`

2) When running the script, make sure that it is the right gcnet_lib.py that is being used.
You can check that with:
```python
gnl.__file__
Out[6]: 'C:\\Users\\bav\\Downloads\\GC-Net-evaluation-master\\GC-Net-evaluation-master\\gcnet_lib.py'
```

**Comment by jasonebox** [comment]
seems the update --all was the ticket!

I now get the plots!

Gee. Thanks!
